apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangoworkflow
  namespace: djangoworkflow
  labels:
    app: djangoworkflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: djangoworkflow
  template:
    metadata:
      labels:
        app: djangoworkflow
    spec:
      containers:
      - name: djangoworkflow
        image: ghcr.io/jdmacd/django-workflow/dev:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "djangoworkflow.settings"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: djangoworkflow
  namespace: djangoworkflow
spec:
  selector:
    app: djangoworkflow
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: djangoworkflow
  namespace: djangoworkflow
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  parentRefs:
  - name: cloudflare
    kind: Gateway
    group: gateway.networking.k8s.io
    namespace: kube-system
    sectionName: https
  hostnames:
  - "djangoworkflow.jtec.xyz"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: djangoworkflow
      kind: Service
      port: 80
